---
- hosts: all
  gather_facts: no
  connection: ssh
  tasks:
  - name: Update System
    dnf:
      name: "*"
      state: latest

  - name: Restart system to reboot to newest kernel
    shell: "sleep 5 && reboot"
    async: 1
    poll: 0

  - name: Wait for 10 seconds
    pause:
      seconds: 10

  - name: Wait for the system to reboot
    wait_for_connection:
      connect_timeout: 20
      sleep: 5
      delay: 5
      timeout: 60

...
