---
- hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  gather_facts: no
  connection: ssh
  tasks:
   - name: add user "roberto"
     user:
       name: roberto
       comment: hernandez sanabria
       password: $6$gpQYSfzrkxzAJJ1o$Og2bQbaSdQ2grvIAsl/eQOkHGIAnTSl4PgHUHKd/Js05AuTpOoQIJqfyxMkeeGM6AnZSQdrpOPVsFzrxl6h68/
       uid: 1000
       group: users
       groups: wheel
       append: yes
       state: present
       shell: /bin/bash

   - name: add SSH key
     authorized_key:
       user: roberto
       state: present
       key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDIzsF+j3zG9S7EHm3yeYPPb4QU/cFShjUEWLHG5TJRgP0Vbo9cogcO04nRHMwshGAtVoiGeMWN6HbwCwgdFTF3TQLeBq6hgHNVbX0LI1M056L7tPpLSfEmhzlAmgYr+2Nj3OhhJ6HhZneTu/+GEqpiEC/5Zivt+SaAd/CbqBRS4egKjIeuOQi4/dWDPmE4ZtCy/hiAo22hNcabhFQORQHKpyHTfcTmySLVnr0ICZ+AF5SnMqg4ven+VoZkXUfpn+LfMo5AOrmg5ZqboO+0+yPVHCIsvXEdn0e68OG+EwMmRKRlP74lNxHkXcuDkiigzdShNAhGI0lxDN+zrZoCqQT2vK3k8Rj1szMOrQZEcGO4XylXHRlzgzM753jD71MSh0QQEfA93aZr4EmLjsNN4nU1VGdyNRQ7DJ+2S8P1qoiW0XBWwqMvUWYs6R+iNrICt68Iqbv/c86GN5ztFWI8b2+9AWCLrQ6XnRmvhzmJU8lcTsHsmqWiHNACR7QELoVQ4x8= roberto@lap-kiro
...
